rpsbb/Controllers/RootController.cs
using ASE.Data;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;
using System.Threading.Tasks;
using System.Web.Script.Serialization;

using ASE.MVC;

using rps.Data;
using rps.SignalR;
using Newtonsoft.Json;
using rpsbb.MVC.Data;

namespace rps.Controllers
{
    [Authorize]
    public class RootController : ControllerAdv<DB>
    {

        // GET: Root
        public ActionResult Index()
        {
            //return File("index.html", "text/html");
            //if (Request.IsAuthenticated)
                //return Redirect("index.html");
                //return Redirect("admin.html");
            //else
                //return Redirect("admin.html");
            return View();
        }

        [AllowAnonymous]
        public async Task<ActionResult> Sync(Guid id)
        {
            //Synchronization.Start(id);

            return Content("Sync started: ");
        }

        [AllowAnonymous]
        public ActionResult Test(string p1, string p2)
        {
            db.Alarms.FirstOrDefault(); 
            return new EmptyResult();
        }

        [AllowAnonymous]
        public ActionResult SignalR()
        {
            return View();
        }

        public ActionResult InitDB()
        {
            AutoMigrationInit.Configure(db);

            return new EmptyResult();
        }

        [AllowAnonymous]
        public JsonResult SignalRAlarm(int code, int state, Guid deviceId)
        {
            var z = db.Zones.FirstOrDefault();
            if (z == null)
            {
                z = new ZoneModel { Id = Guid.NewGuid(), Name = "Zone 1" };
                db.Zones.Add(z);
            }

            var d = db.Devices.FirstOrDefault(x => x.Id == deviceId);
            if (d == null)
            {
                d = new DeviceModel { Id = Guid.NewGuid(), /* Name = "Device 1", DisplayZoneId = z.Id*/ };
                db.Devices.Add(d);
            }
            var m = new AlarmModel { Id = Guid.NewGuid(), TypeId = 1, Begin = DateTime.Now };
            db.Alarms.Add(m);

            db.SaveChanges();

            var jsonResult = new JsonResult
            {
                JsonRequestBehavior = System.Web.Mvc.JsonRequestBehavior.AllowGet,
                Data = m
            };


            var hub = Microsoft.AspNet.SignalR.GlobalHost.ConnectionManager.GetHubContext<HubGeneral>();
            hub.Clients.All.onAlarm(new JavaScriptSerializer().Serialize(jsonResult.Data));

            return jsonResult;
        }

        [AllowAnonymous]
        [HttpPost]
        public ActionResult SqlManager(string t, string a, string i)
        {
            var hub = Microsoft.AspNet.SignalR.GlobalHost.ConnectionManager.GetHubContext<HubGeneral>();

            if (t.ToLower() == "alarms")
                hub.Clients.Group("alarms").onAlarm(JsonConvert.SerializeObject(db.Alarms.Find(int.Parse(i))));

            return new EmptyResult();
        }

        [AllowAnonymous]
        [HttpPost]
        public ActionResult SetSqlGate(string url)
        {
            db.Database.ExecuteSqlCommand(String.Format("ALTER PROCEDURE SPRemoteNotifierL @url NVARCHAR (MAX) AS BEGIN DECLARE @S varchar(max); SET @S = Concat('{0}', @url); EXEC SPRemoteNotifier @S END;", url));

            return RedirectToAction("SignalR");
        }

        [AllowAnonymous]
        public ActionResult CallCenter(bool? user)
        {
            if (!user.HasValue)
                return View("CallCenterOperator");

            return View();
        }

        public ActionResult Settings()
        {
            return View();
        }

        [HttpPost]
        [AllowAnonymous]
        public ActionResult RemoteNotifier(string t, string a, string i)
        {
            var hub = Microsoft.AspNet.SignalR.GlobalHost.ConnectionManager.GetHubContext<HubGeneral>();
            hub.Clients.Group("RN_" + t).onRemoteNotifier(t, a, i);

            return new EmptyResult();
        }
    }
}

rpsbb/Views/Root/CallCenter.cshtml
@{
    ViewBag.Title = "CallCenter";
}

<script src="@Url.Content("~/Scripts/adapter.js")"></script>
<script src="@Url.Content("~/Scripts/file-transfer.js")"></script>
<script src="@Url.Content("~/Scripts/jquery.signalR-2.2.0.js")"></script>
<script src="~/signalr/hubs"></script>

<div class="row form-group">
</div>

<div class="row form-group">
    <button id="call" class="btn btn-primary" onclick="callStartStopCancel()">Start call</button>
</div>

<div class="row form-group">
    <div class="col-md-6">
        <video id="localVideo" autoplay muted></video>
    <div class="col-md-6">
    </div>
        <video id="remoteVideo" autoplay></video>
    </div>
</div>

<div class="row form-group">
    <div class="col-md-12 well" id="msg">

    </div>
</div>


<script>
    navigator.getUserMedia = navigator.getUserMedia || navigator.mozGetUserMedia || navigator.webkitGetUserMedia;
    var hub = $.connection.hubCallCentral;
    var operatorId;
    var pc;
    var dc;

    $.connection.hub.start().done(function () {
        L("ID", $.connection.hub.id);
    });

    hub.client.onConnected = function (id, user) {
        L("connected", id, user);
    };

    hub.client.onDisconnected = function (id) {
        L("disconnected", id);
        if (id == operatorId)
            callStartStopCancel();
    };

    hub.client.onClientCallStart = function (id, msg) {
        L("onClientCallStart", id, msg);
    };


    hub.client.onAnswer = function (id) {
        operatorId = id;
        L("onAnswer", id);
        $("#call").removeClass("btn-warning");
        $("#call").addClass("btn-danger");
        $("#call").html("Cancel call");

        pc = new RTCPeerConnection(null, null);
        dc = null;

        pc.addStream(localStream);

        //pc.onconnection = handleOnconnection;
        //pc.onsignalingstatechange = onsignalingstatechange;
        //pc.oniceconnectionstatechange = oniceconnectionstatechange;
        //pc.onicegatheringstatechange = onicegatheringstatechange;
        pc.onaddstream = gotRemoteStream;
        pc.onicecandidate = onicecandidate;

        try {
            var fileReceiver1 = new FileReceiver();
            dc = pc.createDataChannel('test', { reliable: true });
            dc.onopen = function (e) { console.log('DC data channel connect'); }
            dc.onmessage = function (e) { console.log("DC Got message (pc1)", e.data); };
        } catch (e) { console.warn("No data channel (pc1)", e); }

        //START CREATE OFFER
        pc.createOffer(function (desc) {
            pc.setLocalDescription(desc, function () {
            }, function () { });
        }, function () { console.warn("Couldn't create offer"); });
    };
    
    function gotRemoteStream(event) {
        L("onaddstream", event);
    };

    function onicecandidate(e) {
        if (e.candidate == null) {
            hub.server.offerClient2Operator(JSON.stringify(pc.localDescription));
        }
    };

    var localStream;

    $(function () {
        navigator.getUserMedia(
            {
                audio: true, video: true
            },
            function gotStream(stream) {
                document.getElementById("localVideo").src = URL.createObjectURL(stream);
                localStream = stream;
            },
            function (error) {
            }
        );
    });


    function callStartStopCancel() {
        if ($("#call").hasClass("btn-primary")) {
            $("#call").removeClass("btn-primary");
            $("#call").addClass("btn-warning");
            $("#call").html("Stop call");
            hub.server.callStart("I need help!");
        }
        else if ($("#call").hasClass("btn-warning")) {
            $("#call").removeClass("btn-warning");
            $("#call").addClass("btn-primary");
            $("#call").html("Start call");
            hub.server.callStop("Buy, buy!");
        }
        else if ($("#call").hasClass("btn-danger")) {
            $("#call").removeClass("btn-danger");
            $("#call").addClass("btn-primary");
            $("#call").html("Start call");
            hub.server.callStop("Buy, buy!");
        }
}

    function L() {
        s = "<li>";
        s += "<b>";
        s += arguments[0];
        s += ": </b>";

        for (var i = 1; i < arguments.length; i++) {
            s += "[";
            s += arguments[i];
            s += "] ";
        }
        s += "</li>";

        $("#msg").append(s);
    }
</script>

rpsbb/Views/Root/CallCenterOperator.cshtml
@{
    ViewBag.Title = "CallCenter";
}

<script src="@Url.Content("~/Scripts/adapter.js")"></script>
<script src="@Url.Content("~/Scripts/file-transfer.js")"></script>
<script src="@Url.Content("~/Scripts/jquery.signalR-2.2.0.js")"></script>
<script src="~/signalr/hubs"></script>

<div class="row form-group">
</div>

<div class="row form-group" id="calls">
</div>

<div class="row form-group">
    <div class="col-md-12 well" id="msg">

    </div>
</div>


<script>
    var hub = $.connection.hubCallCentral;

    $.connection.hub.start().done(function () {
        L("ID", $.connection.hub.id);
        hub.server.joinAsOperator();
    });

    hub.client.onConnected = function (id, user) {
        L("connected", id, user);
    };

    hub.client.onDisconnected = function (id) {
        L("disconnected", id);
    };

    hub.client.onClientCallStart = function (id, msg) {
        L("onClientCallStart", id, msg);
        $("#calls").append('<li><button class="btn btn-primary" onclick="Answer(\'' + id +'\');" id="id' + id + '">Answer ' + id + '</button></li>')
    };

    hub.client.onClientCallStop = function (id, msg) {
        L("onClientCallStop", id, msg);
        $("#id" + id).parent().remove();
    };
    
    function Answer(id) {
        hub.server.answer(id).done(function (r) {
            L("answer()", r);
        });
    }

    hub.client.onClientOffer = function (id, offer) {
        L("onClientOffer", id, msg);
    };    

    function L() {
        s = "<li>";
        s += "<b>";
        s += arguments[0];
        s += ": </b>";

        for (var i = 1; i < arguments.length; i++) {
            s += "[";
            s += arguments[i];
            s += "] ";
        }
        s += "</li>";

        $("#msg").append(s);
    }
</script>

rpsbb/Views/Root/Settings.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">

    <title>ЦУ</title>
    <link href="/bower_components/font-awesome/css/font-awesome.css" rel="stylesheet">
    <link href="/settings/styles/css/bs.css" rel="stylesheet">
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700&subset=latin,cyrillic-ext,cyrillic'
          rel='stylesheet' type='text/css'>
    <link href="/bower_components/bootstrap-select/dist/css/bootstrap-select.min.css" rel="stylesheet">
    <link href="/bower_components/backbone-forms/distribution.amd/templates/bootstrap3.css" rel="stylesheet">
    <link href="/bower_components/iCheck/skins/square/square.css" rel="stylesheet">

    <link href="/settings/styles/css/custom.css" rel="stylesheet">


    <link href="/settings/styles/css/modals.css" rel="stylesheet">
    <link rel="stylesheet" href="/common/vendors/jquery-ui-rotatable/jquery.ui.rotatable.css">
    <link rel="stylesheet" href="/bower_components/select2/dist/css/select2.css">

</head>

<body style="overflow: hidden;">


    <script src="bower_components/modernizr/modernizr.js"></script>
    <script type="text/javascript" src="/common/vendors/svgedit/embedapi.js"></script>

    <script data-main="/settings/scripts/init" src="bower_components/requirejs/require.js"></script>


</body>
</html>

rpsbb/Views/Root/SignalR.cshtml
@{
    ViewBag.Title = "SignalR";
}

<script src="@Url.Content("~/MVCScripts/jquery.signalR-2.2.0.js")"></script>
<script src="~/signalr/hubs"></script>

<h2>SignalR ID:<span></span></h2>

<div class="row form-group">
    @using (Html.BeginForm("SetSqlGate", "Root", FormMethod.Post))
    {
        @Html.TextBox("url", "http://localhost/root/sqlmanager/", new { style = "width: 300px;"})
        
        <input type="submit" class="btn btn-primary" value="Set sql2web gate"/>
    }
</div>

<div class="row form-group">
    <button class="btn btn-primary" onclick="onAlarmStart()">Start onAlarm</button>
    <button class="btn btn-warning" onclick="onAlarmStop()">Stop onAlarm</button>
</div>

<div class="row form-group">
    <div class="col-md-12 well" id="msg">

    </div>
</div>

<script>
    $.connection.hub.logging = true;
    var hub = $.connection.hubGeneral;

    $(function () {
        hub.client.onConnected = function (userId) {
            L("Connected", userId);
        };

        hub.client.onDisconnected = function (userId) {
            L("Disconnected", userId);
        };

        hub.client.onReconnected = function (userId) {
            L("Reconnected", userId);
        };

        hub.client.onJoinInGroup = function (userId, group) {
            L("JoinInGroup", userId, "in", group);
        };

        hub.client.onLeaveGroup = function (userId, group) {
            L("LeaveGroup", userId, "from", group);
        };

        hub.client.onLeaveGroup = function (userId, group) {
            L("LeaveGroup", userId, "from", group);
        };

        hub.client.onMessageGroup = function (userId, group, message) {
            L("MessageGroup", userId, "group", group, "message", message);
        };

        hub.client.onMessageAll = function (userId, message) {
            L("MessageAll", userId, "message", message);
        };

        hub.client.onAlarm = function (data) {
            L("MessageAll", data);
        };
        hub.client.onRemoteNotifier = function (table, action, id) {
            L("RemoteNotifier", table, action, id);
        };        

        $.connection.hub.start().done(function () {
            $("h2 > span").html($.connection.hub.id);

            hub.server.joinInGroup("test");
            hub.server.joinInGroup("RN_DeviceModel");
            hub.server.joinInGroup("RN_DeviceCMModel");
            hub.server.messageGroup("test", "Hi Group!");
            hub.server.messageAll("Hi All!");
        });
    });

    function L()
    {
        s = "<li>";
        s += "<b>";
        s += arguments[0];
        s += ": </b>";

        for (var i = 1; i < arguments.length; i++) {
            s += "[";
            s += arguments[i];
            s += "] ";
        }
        s += "</li>";

        $("#msg").append(s);
    }

    function onAlarmStart() {
        hub.server.joinInGroup("alarms");
    }

    function onAlarmStop() {
        hub.server.leaveGroup("alarms");
    }
</script>